-- MySQL Script generated by MySQL Workbench
-- Tue Sep 17 15:14:19 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `cod_fun` INT NOT NULL AUTO_INCREMENT,
  `nome_fun` VARCHAR(45) NOT NULL,
  `login_fun` VARCHAR(45) NOT NULL,
  `senha_fun` VARCHAR(45) NOT NULL,
  `status_fun` VARCHAR(10) NOT NULL DEFAULT 'ATIVO',
  `funcao_fun` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_fun`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `cod_ven` INT NOT NULL AUTO_INCREMENT,
  `data_ven` DATE NOT NULL,
  `funcionario_cod_fun` INT NOT NULL,
  PRIMARY KEY (`cod_ven`),
  INDEX `fk_venda_funcionario_idx` (`funcionario_cod_fun` ASC) VISIBLE,
  CONSTRAINT `fk_venda_funcionario`
    FOREIGN KEY (`funcionario_cod_fun`)
    REFERENCES `mydb`.`funcionario` (`cod_fun`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`amplificador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`amplificador` (
  `cod_amp` INT NOT NULL AUTO_INCREMENT,
  `tipo_amp` VARCHAR(45) NOT NULL,
  `marca_amp` VARCHAR(45) NOT NULL,
  `modelo_amp` VARCHAR(45) NOT NULL,
  `preco_amp` DECIMAL(10,2) NOT NULL,
  `foto_amp` VARCHAR(100) NOT NULL,
  `fila_compra_amp` CHAR(1) NOT NULL DEFAULT 'N',
  `venda_cod_ven` INT NULL,
  PRIMARY KEY (`cod_amp`),
  INDEX `fk_amplificador_venda1_idx` (`venda_cod_ven` ASC) VISIBLE,
  CONSTRAINT `fk_amplificador_venda1`
    FOREIGN KEY (`venda_cod_ven`)
    REFERENCES `mydb`.`venda` (`cod_ven`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
